image: node:20.11.1-bullseye

stages:
  - test
  - build
  - deploy

test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apt update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm ci
    - npm run test -- --no-watch --browsers=ChromeHeadlessCI

build:
  stage: build
  cache:
      paths:
        - node_modules/
        - dist/
  only:
      - main
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
      - node_modules/

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none # Do not clone git repo
    NODE_ENV: production
    PUBLIC_URL: https://gitlab.com/julianruano/evaluation_system_frontend
  script:
    - rm -rf public
    - cp dist/evaluation_system_frontend/browser/index.html dist/evaluation_system_frontend/browser/404.html
    - cp dist/evaluation_system_frontend/browser/* dist/
    - mv dist public
  only:
    - main
  artifacts:
    paths:
      - public


